

package Principal;

import Deposito.Deposito;
import Entidades.Conta;
import Extrato.Extrato;
import PIX.PIX;
import Transferencia_Eletronica.Transferencia_Eletronica;
import javax.swing.ImageIcon;


public class Principal extends javax.swing.JFrame {

    Conta conta = new Conta();
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        
        
    }
  

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblConta = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        tfTipoConta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Hobo Std", 0, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nu");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 10, 90, 80);

        jLabel2.setFont(new java.awt.Font("Linux Libertine G", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TADS");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 40, 70, 30);

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Nome:");
        jPanel1.add(lblNome);
        lblNome.setBounds(220, 50, 300, 17);

        lblConta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblConta.setForeground(new java.awt.Color(255, 255, 255));
        lblConta.setText("Conta:");
        jPanel1.add(lblConta);
        lblConta.setBounds(550, 50, 180, 17);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jButton3.setBackground(new java.awt.Color(153, 0, 153));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgens/tranferencia.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(50, 70, 140, 60);

        jButton7.setBackground(new java.awt.Color(153, 0, 153));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgens/Extrato.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setPreferredSize(new java.awt.Dimension(51, 49));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(590, 70, 140, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Exrato");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(640, 130, 50, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Transferência");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(80, 130, 90, 20);

        jButton8.setBackground(new java.awt.Color(153, 0, 153));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgens/depositar.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setPreferredSize(new java.awt.Dimension(51, 49));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(410, 70, 140, 60);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Depositar");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(450, 130, 80, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("PIX");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(290, 130, 30, 20);

        jButton4.setBackground(new java.awt.Color(153, 0, 153));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgens/pix.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(230, 70, 140, 60);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgens/fundo.png"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(270, 180, 530, 210);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgens/Propaganda.png"))); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(40, 200, 290, 190);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 90, 800, 400);

        jButton5.setText("jButton1");
        jPanel1.add(jButton5);
        jButton5.setBounds(230, 160, 140, 40);

        tfTipoConta.setEditable(false);
        jPanel1.add(tfTipoConta);
        tfTipoConta.setBounds(610, 20, 160, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Transferencia_Eletronica form = new Transferencia_Eletronica();
        form.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        Extrato form = new Extrato();
        form.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    Deposito form = new Deposito();
    form.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       PIX form = new PIX();
       form.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
         Conta conta = new Conta();
          conta.getSalario();
      
        if(conta.tipoConta()){
          tfTipoConta.setText("Conta Comum");           
        }else{
            tfTipoConta.setText("Conta Premium");         
        }
    
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblConta;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField tfTipoConta;
    // End of variables declaration//GEN-END:variables

}
