
package Login;

import Cadastro.Cadastro;
import Principal.Principal;
import java.awt.Color;
import static java.awt.Color.red;

/**
 *
 * @author danil
 */
public class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();
       setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfCPF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfSenha = new javax.swing.JPasswordField();
        btnCadastrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 570));
        setMinimumSize(new java.awt.Dimension(400, 570));
        setPreferredSize(new java.awt.Dimension(400, 570));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 570));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 570));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 570));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 570));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Hobo Std", 0, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nu");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 20, 90, 80);

        jLabel2.setFont(new java.awt.Font("Linux Libertine G", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TADS");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 50, 70, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Não sou cliente");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(100, 320, 100, 20);

        jLabel4.setFont(new java.awt.Font("Source Sans Pro Light", 1, 18)); // NOI18N
        jLabel4.setText("Faça seu login");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(90, 30, 120, 30);

        tfCPF.setMaximumSize(new java.awt.Dimension(7, 22));
        tfCPF.setMinimumSize(new java.awt.Dimension(7, 22));
        tfCPF.setPreferredSize(new java.awt.Dimension(7, 22));
        jPanel2.add(tfCPF);
        tfCPF.setBounds(20, 90, 260, 40);

        jLabel5.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        jLabel5.setText("CPF");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(22, 70, 30, 20);

        tfSenha.setMaximumSize(new java.awt.Dimension(7, 22));
        tfSenha.setMinimumSize(new java.awt.Dimension(7, 22));
        tfSenha.setPreferredSize(new java.awt.Dimension(7, 22));
        jPanel2.add(tfSenha);
        tfSenha.setBounds(20, 160, 260, 40);

        btnCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setFont(new java.awt.Font("Source Sans Pro Light", 1, 14)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(153, 0, 153));
        btnCadastrar.setBorder(null);
        btnCadastrar.setBorderPainted(false);
        btnCadastrar.setContentAreaFilled(false);
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.setLabel("Cadastrar");
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseReleased(evt);
            }
        });
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCadastrar);
        btnCadastrar.setBounds(110, 330, 70, 40);

        jLabel6.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        jLabel6.setText("Senha");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(22, 140, 50, 20);

        btnContinuar.setBackground(new java.awt.Color(255, 255, 255));
        btnContinuar.setFont(new java.awt.Font("Source Sans Pro Light", 1, 18)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(153, 0, 153));
        btnContinuar.setText("Continuar");
        btnContinuar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153)));
        btnContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        jPanel2.add(btnContinuar);
        btnContinuar.setBounds(20, 220, 260, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(42, 100, 300, 380);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
       Cadastro cad = new Cadastro();
       cad.setVisible(true);
       dispose();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnCadastrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseReleased
        btnCadastrar.setForeground(Color.RED);
    }//GEN-LAST:event_btnCadastrarMouseReleased

    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarMouseClicked

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        Principal form = new Principal();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfCPF;
    private javax.swing.JPasswordField tfSenha;
    // End of variables declaration//GEN-END:variables
}
